#pragma config(Motor,  port2,           YWire,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           chainTop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           chainBottom,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define MAX_SPEED 127

bool bYWire = true;
task main()
{
	clearTimer(T1);
	while(time1[T1] < 1000) {
		if(bYWire)
			motor[YWire] = MAX_SPEED;
		else { motor[chainBottom] = MAX_SPEED; motor[chainTop] = MAX_SPEED; }
	}
}
