#pragma config(Motor,  port1,           piston,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		motor[piston] = 127;
	}

}
