#pragma config(Motor,  port1,           dBackRight,    tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           dBackLeft,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           dFrontRight,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           dFrontLeft,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           pistonLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           pistonRight,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void stopDrive(){
	motor[dBackRight] = NO_SPEED;
	motor[dBackLeft] = NO_SPEED;
	motor[dFrontLeft] = NO_SPEED;
	motor[dFrontRight] = NO_SPEED;
}

void moveForward(float time, int speed){
	motor[dBackRight] = speed;
	motor[dBackLeft] = speed;
	motor[dFrontLeft] = speed;
	motor[dFrontRight] = speed;
	wait1Msec(time);
	stopDrive();
}

void moveBackward(float time, int speed){
	motor[dBackRight] = speed *-1;
	motor[dBackLeft] = speed *-1;
	motor[dFrontLeft] = speed *-1;
	motor[dFrontRight] = speed *-1;
	wait1Msec(time);
	stopDrive();
}

void leftTurn(float time, int speed){
	motor[dBackRight] = speed;
	motor[dFrontRight] = speed;
	wait1Msec(time);
	stopDrive();
}

void rightTurn(float time, int speed){
	motor[dBackLeft] = speed;
	motor[dFrontLeft] = speed;
	wait1Msec(time);
	stopDrive();
}

void leftSpin(float time, int speed){
	motor[dFrontRight] = speed;
	motor[dBackRight] = speed;
	motor[dBackLeft] = speed *-1;
	motor[dFrontLeft] = speed *-1;
	wait1Msec(time);
	stopDrive();
}

void rightSpin(float time, int speed){
	motor[dFrontRight] = speed *-1;
	motor[dBackRight] = speed *-1;
	motor[dBackLeft] = speed;
	motor[dFrontLeft] = speed;
	wait1Msec(time);
	stopDrive();
}

void rightVeer(float time, int speed, int offset) {
	motor[dBackLeft] = speed;
	motor[dFrontLeft] = speed;
	motor[dBackRight] = (speed *-1) - offset;
	motor[dFrontRight] = (speed *-1) - offset;
	wait1Msec(time);
	stopDrive();
}

void leftVeer(float time, int speed, int offset) {
	motor[dBackRight] = speed;
	motor[dFrontRight] = speed;
	motor[dBackLeft] = (speed *-1) - offset;
	motor[dFrontLeft] = (speed *-1) - offset;
	wait1Msec(time);
	stopDrive();
}

/*void feedBall(float time = FEED_LENGTH)
{
	mainLift = STARTED;
	motor[lift] = MAX_SPEED;
	motor[pistonLeft] = 100;
	motor[pistonRight] = 100;
	wait1Msec(time);
	mainLift = READY; // Assuming ball has fed into the piston
	// TODO: Add actual way to check we have a ball (HW & SW)
	motor[lift] = NO_SPEED;
}*/

bool fireBall(bool forceShot)
{
	if(forceShot)
		mainLift = READY;

	if(mainLift != READY)
		return false; // Ball shot failed, we return false
	// We want the ball to be fed first

	// TODO: Add adjustment function for angle of shot
	// adjustAngle(position);

	motor[pistonLeft] = MAX_SPEED;
	motor[pistonRight] = MAX_SPEED;
	motor[lift] = MAX_SPEED;
	wait1Msec(PISTON_LENGTH); // Placeholder for time
	motor[lift] = NO_SPEED;
	motor[pistonLeft] = NO_SPEED;
	motor[pistonRight] = NO_SPEED;

	mainLift = STOPPED; // Reset lift for next shot

	return true; // Shot completed successfully
}
