#pragma config(Motor,  port1,           dBackRight,    tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           dBackLeft,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           dFrontRight,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           dFrontLeft,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           pistonLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           pistonRight,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// TODO: FINISH THIS

void getInput()
{
	if(vexRT[Btn5D]) doAuto(RED_FRONT);
	if(vexRT[Btn5U]) doAuto(RED_BACK);
	if(vexRT[Btn6D]) doAuto(BLUE_FRONT);
	if(vexRT[Btn6U]) doAuto(BLUE_BACK);
}

void doAuto(Autoselection a)
{
}
