#pragma config(Motor,  port1,           dBackRight,    tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           dBackLeft,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           dFrontRight,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           dFrontLeft,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           pistonLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           pistonRight,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef AUTO_SELECTOR_H_
#define AUTO_SELECTOR_H_

// TODO: FINISH THIS

void getInput()
{
	if(vexRT[Btn5D]) currentSelection = RED_FRONT;
	if(vexRT[Btn5U]) currentSelection = RED_BACK;
	if(vexRT[Btn6D]) currentSelection = BLUE_FRONT;
	if(vexRT[Btn6U]) currentSelection = BLUE_BACK;
}

void doAuto()
{
	switch(currentSelection)
	{
	case RED_FRONT:
		break;

	case RED_BACK:
		moveForward(700, MAX_SPEED);
		rightSpin(800, MAX_SPEED);
		moveBackward(900, MAX_SPEED);
		if(!fireBall(false)) // Forcing true for testing purposes
			fireBall(true);
		break;
	case BLUE_FRONT:
		break;

	case BLUE_BACK:
		break;

	default:
		break;
	}
}

#endif
