#pragma config(Motor,  port2,           driveRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           piston,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           elevator,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "motors.h"

void pre_auton()
{
	bDisplayCompetitionStatusOnLcd = false;
	bStopTasksBetweenModes = true;

	if(false){ // This code will never run
		dualJoystick();
	}
}

task autonomous()
{

}

task usercontrol()
{
	while(true)
	{
		mapJoystick();
	}
}
