#pragma config(Motor,  port1,           dBackLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           dBackRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           dFrontRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           dFrontLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftLower,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftUpper,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           piston,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "motors.h"

void pre_auton()
{
	bDisplayCompetitionStatusOnLcd = false;
	bStopTasksBetweenModes = true;

	if(false){ // This code will never run
		dualJoystick();
	}
}

task autonomous()
{

}

task usercontrol()
{
	while(true)
	{
		mapJoystick();
	}
}
