#pragma config(Motor,  port1,           dBackRight,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           piston,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           dFrontLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           flipper,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           dFrontRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           dBackLeft,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !! *//

#pragma platform(VEX2)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

#include "motors.h"
#include "auto_functions.h"

void pre_auton()
{

}


task autonomous()
{
	moveBackward(500, MAX_SPEED);
	fireBall(true);
	moveBackward(2000, MAX_SPEED);
	moveForward(1000, MAX_SPEED);
	leftSpin(600, MAX_SPEED);
	motor[flipper] = 127;
	wait1Msec(500);
	moveForward(500, MAX_SPEED);
	motor[flipper] = -127;
	wait1Msec(500);
	rightSpin(600, MAX_SPEED);
	moveForward(1500, MAX_SPEED);
}

task usercontrol()
{
	while (true)
	{
		mapJoystick();
	}
}
