#pragma config(Motor,  port1,           dBackRight,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           piston,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           dFrontLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           flipper,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           dFrontRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           dBackLeft,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// More functions, being used for skills

void park(bool isRed)
{
	moveBackward(600, MAX_SPEED);
	if(isRed) rightSpin(400, MAX_SPEED);
	else leftSpin(400, MAX_SPEED);
	moveBackward(2500, MAX_SPEED);
}

void flipCap(float time)
{
	motor[flipper] = -63;
	moveForward(time, MAX_SPEED);
	motor[flipper] = 63;
}

void _skills_old()
{
	moveBackward(500, MAX_SPEED);
	fireBall(true);
	moveBackward(2000, MAX_SPEED);
	moveForward(1000, MAX_SPEED);
	leftSpin(600, MAX_SPEED);
	motor[flipper] = 127;
	wait1Msec(500);
	moveForward(500, MAX_SPEED);
	motor[flipper] = -127;
	wait1Msec(500);
	rightSpin(600, MAX_SPEED);
	moveForward(1500, MAX_SPEED);
}
