#pragma config(Motor,  port2,           fLeft,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fRight,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           bLeft,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           bRight,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           fDisk,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           launcher,      tmotorVex393_MC29, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																																				//
//																							 	AUTONOMOUS FUNCTIONS					     																											//
//																																																																				//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void stopRobot()
{
	motor[bLeft] = 0;
	motor[bRight] = 0;
	motor[fLeft] = 0;
	motor[fRight] = 0;
}

void moveForward(int speed, int durationMilliseconds)
{
	motor[bLeft] = speed;
	motor[bRight] = speed;
	motor[fLeft] = speed;
	motor[fRight] = speed;
	wait1Msec(durationMilliseconds);
	stopRobot();
}

void moveBackward(int speed, int durationMilliseconds)
{
	motor[bLeft] = -1 * speed;
	motor[bRight] = -1 * speed;
	motor[fLeft] = -1 * speed;
	motor[fRight] = -1 * speed;
	wait1Msec(durationMilliseconds);
	stopRobot();
}

void turnLeft(int speed, int durationMilliseconds)
{
	motor[bLeft] = -1 * speed;
	motor[bRight] = speed;
	motor[fLeft] = -1 * speed;
	motor[fRight] = speed;
	wait1Msec(durationMilliseconds);
	stopRobot();
}

void turnRight(int speed, int durationMilliseconds)
{
	motor[bLeft] = speed;
	motor[bRight] = -1 * speed;
	motor[fLeft] = speed;
	motor[fRight] = -1 * speed;
	wait1Msec(durationMilliseconds);
	stopRobot();
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																																				//
//																								AUTONOMOUS (FLIP DISK)     																															//
//																																																																				//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//1 point per disk

//DEFAULT CLAW DOWN
/*
	moveForward(,);	//FORWARD 1/2 BOX
	turnRight(,);	//TURN RIGHT
	moveForward(,);	//FORWARD 1/2 BOX
	liftArm(,);	//RAISE ARM
*/
//FIN

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																																				//
//																								AUTONOMOUS (FLAGS)																																			//
//																																																																				//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//1 point per flag

 //DEFAULT CLAW NEUTRAL
/*
	turnRight(,);	//TURN RIGHT
	moveForward(,);	//FORWARD 1 1/2 BOX
	moveBackward(,);	//BACKWARDS 1/2 BOX
	turnLeft(,);	//TURN LEFT
	moveForward(,);	//FORWARD 1 1/2 BOX
	turnRight(,);	//TURN 1/2 RIGHT
	moveForward(,);	//FORWARD 1/2 BOX
*/
 //FIN
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																																				//
//																								BOTH JOYSTICKS CONTROLS																																	//
//																																																																				//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  while (true)
  {
		//Joystick Control
		motor[fLeft] = vexRT[Ch3];
		motor[fRight] = vexRT[Ch2];
		motor[bLeft] = vexRT[Ch3];
		motor[bRight] = vexRT[Ch2];

		//5U & 5D - Flip Disk
	  if(vexRT[Btn5U] == 1) {
			motor[fDisk] = 100;}
		else if (vexRT[Btn5D]) {
			motor[fDisk] = -100;}
    else {
			motor[fDisk] = 0;
		}

		//6U & 6D Lift
		if(vexRT[Btn6U] == 1) {
			motor[Lift] = 100;}
		else if (vexRT[Btn6D]) {
			motor[Lift] = -100;}
    else {
			motor[Lift] = 0;
		}

	/*	//6U - Launcher
 		if (vexRT[Btn6U] == 1) {
		  motor[launcher] = -127;
  	}
		else {
			motor[launcher] = 0;
		}
	*/

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																																				//
//																								SINGLE JOYSTICKS CONTROLS																																//
//																																																																				//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	//Joystick Control
		//Forward / Backward
		motor[fLeft] = vexRT[Ch2];
		motor[fRight] = vexRT[Ch2];
		motor[bLeft] = vexRT[Ch2];
		motor[bRight] = vexRT[Ch2];

		//Turns (code below is turning right, reversed is turning left)
		motor[fLeft] = vexRT[Ch1];
		motor[fRight] = vexRT[Ch1]*-1;
		motor[bLeft] = vexRT[Ch1];
		motor[bRight] = vexRT[Ch1]*-1;

		//Flip disk
		motor[fDisk] = vexRT[Ch4];

		//Lift
		motor[Lift] = vexRT[Ch3];



		}
}
