#pragma config(Motor,  port2,           fLeft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           fRight,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           bLeft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           bRight,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           fDisk,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*	You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void stopRobot()
{
	motor[bLeft] = 0;
	motor[bRight] = 0;
	motor[fLeft] = 0;
	motor[fRight] = 0;
}

void moveForward(int speed, int durationMilliseconds)
{
	motor[bLeft] = speed;
	motor[bRight] = speed;
	motor[fLeft] = speed;
	motor[fRight] = speed;
	wait1Msec(durationMilliseconds);
	stopRobot();
}

void moveBackward(int speed, int durationMilliseconds)
{
	motor[bLeft] = -1 * speed;
	motor[bRight] = -1 * speed;
	motor[fLeft] = -1 * speed;
	motor[fRight] = -1 * speed;
	wait1Msec(durationMilliseconds);
	stopRobot();
}

void turnLeft(int speed, int durationMilliseconds)
{
	motor[bLeft] = -1 * speed;
	motor[bRight] = speed;
	motor[fLeft] = -1 * speed;
	motor[fRight] = speed;
	wait1Msec(durationMilliseconds);
	stopRobot();
}

void turnRight(int speed, int durationMilliseconds)
{
	motor[bLeft] = speed;
	motor[bRight] = -1 * speed;
	motor[fLeft] = speed;
	motor[fRight] = -1 * speed;
	wait1Msec(durationMilliseconds);
	stopRobot();
}

task autonomous()
{





}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

  while (true)
  {
	//Joystick Control
		motor[fLeft] = vexRT[Ch3];
		motor[fRight] = vexRT[Ch2];
		motor[bLeft] = vexRT[Ch3];
		motor[bRight] = vexRT[Ch2];


/*
		//6U - Launcher
 		if (vexRT[Btn6U] == 1) {
		  motor[launcher] = -127;
  	}
		else {
			motor[launcher] = 0;
		}
*/

	//5U & 5D - Flip Disk
	  if(vexRT[Btn5U] == 1) {
			motor[fDisk] = 100;}
		else if (vexRT[Btn5D]) {
			motor[fDisk] = -100;}
    else {
			motor[fDisk] = 0;
		}

	//Lift
		if(vexRT[Btn6U] == 1) {
			motor[lift] = 100;}
		else if (vexRT[Btn6D]) {
			motor[lift] = -100;}
    else {
			motor[lift] = 0;
		}

	}
}
