#pragma config(Motor,  port2,           fLeft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           fRight,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           bLeft,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           bRight,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           flipper,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
  bDisplayCompetitionStatusOnLcd = false;
}

task autonomous()
{
  AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
  while (true)
  {
  	//Main Controller Drive
    motor[fRight] =		vexRT[Ch2];
    motor[fLeft] 	=		vexRT[Ch3];
    motor[bRight] =		vexRT[Ch2];
    motor[bLeft] 	=		vexRT[Ch2];

    //Partner Controller Lift&Flip
   	motor[flipper]		=		vexRT[Ch3Xmtr2];
   	motor[liftLeft]		=		vexRT[Ch2Xmtr2];
   	motor[liftRight]	=		vexRT[Ch2Xmtr2];
  }
}
