#pragma config(Sensor, in1,    expander,       sensorAnalog)
#pragma config(Motor,  port2,           expander_motor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	datalogStart();
	datalogDataGroupStart();

	//This file is mainly testing out the datalogging functions
	clearTimer(T1);
	while(time1[T1] < 5000) {
	datalogAddValue(0, sinDegrees(SensorValue[expander]));
	datalogAddValue(1, SensorValue[expander]);
	}

	//	while(true) {
	//		float fExpander = (float)SensorValue[expander] / 270.0;
	//		datalogDataGroupStart();
	//		datalogAddValueWithTimeStamp(1, (int)fExpander);
	//		datalogDataGroupEnd();
	//	}

	datalogDataGroupEnd();
	datalogStop();
}
