#pragma config(Motor,  port2,           frontrightmotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontleftmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backrightmotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backleftmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           fliptable,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           arm1top,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          arm2top,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/

/*                                                                           */

/*        Description: Competition template for VEX EDR                      */

/*                                                                           */

/*---------------------------------------------------------------------------*/



// This code is for the VEX cortex platform

#pragma platform(VEX2)



// Select Download method as "competition"

#pragma competitionControl(Competition)



//Main competition background code...do not modify!

#include "Vex_Competition_Includes.c"





void pre_auton()

{


	bStopTasksBetweenModes = true;
}


void stop_Robot()

{
 motor[frontrightmotor] = 0;
	motor[backrightmotor] = 0;
	motor[frontleftmotor] =0;
	motor[backleftmotor] = 0;



}





task autonomous()

{
	motor[frontrightmotor] = -127;
	motor[backrightmotor] = -127;
	motor[frontleftmotor] = -127;
	motor[backleftmotor] = -127;
	wait1Msec(2500);
	stop_Robot();
	motor[frontrightmotor] = 127;
	motor[backrightmotor] = 127;
	motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(2500);
	stop_Robot();
	motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(1500);
	stop_Robot();
	motor[frontrightmotor] = 127;
	motor[backrightmotor] = 127;
	motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(1000);
	stop_Robot();
  motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(1500);
	stop_Robot();
	motor[frontrightmotor] = 127;
	motor[backrightmotor] = 127;
	motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(2500);
	stop_Robot();



}







task usercontrol()

{





	while (true)

	{


		motor[frontleftmotor]  = vexRT[Ch3];
		motor[backleftmotor]  = vexRT[Ch3];
		motor[frontrightmotor] = vexRT[Ch2];
		motor[backrightmotor] = vexRT[Ch2];


		motor[arm1] = vexRT[Ch2Xmtr2];
		motor[arm2] = vexRT[Ch2Xmtr2];
		motor[arm1top] = vexRT[Ch2Xmtr2];
		motor[arm2top] = vexRT[Ch2Xmtr2];



		motor[fliptable] = vexRT[Ch3Xmtr2];



	}

}
