#pragma config(Motor,  port2,           frontrightmotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontleftmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backrightmotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backleftmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           fliptable,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           arm1top,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          arm2top,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/

/*                                                                           */

/*        Description: Competition template for VEX EDR                      */

/*                                                                           */

/*---------------------------------------------------------------------------*/



// This code is for the VEX cortex platform

#pragma platform(VEX2)



// Select Download method as "competition"

#pragma competitionControl(Competition)



//Main competition background code...do not modify!

#include "Vex_Competition_Includes.c"



/*---------------------------------------------------------------------------*/

/*                          Pre-Autonomous Functions                         */

/*                                                                           */

/*  You may want to perform some actions before the competition starts.      */

/*  Do them in the following function.  You must return from this function   */

/*  or the autonomous and usercontrol tasks will not be started.  This       */

/*  function is only called once after the cortex has been powered on and    */

/*  not every time that the robot is disabled.                               */

/*---------------------------------------------------------------------------*/



void pre_auton()

{

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks

	// running between Autonomous and Driver controlled modes. You will need to

	// manage all user created tasks if set to false.

	bStopTasksBetweenModes = true;
}



	void stop_Robot()

	{

		motor[frontrightmotor] = 0;
		motor[backrightmotor] = 0;
		motor[frontleftmotor] = 0;
		motor[backleftmotor] = 0;
		wait1Msec(1000);



	}

void pre_auton()
{

}



/*---------------------------------------------------------------------------*/

/*                                                                           */

/*                              Autonomous Task                              */

/*                                                                           */

/*  This task is used to control your robot during the autonomous phase of   */

/*  a VEX Competition.                                                       */

/*                                                                           */

/*  You must modify the code to add your own robot specific commands here.   */

/*---------------------------------------------------------------------------*/



task autonomous()

{
	motor[frontrightmotor] = -127;
	motor[backrightmotor] = -127;
	motor[frontleftmotor] = -127;
	motor[backleftmotor] = -127;
	wait1Msec(1000);
	stop_Robot();
	motor[frontrightmotor] = 127;
	motor[backrightmotor] = 127;
	motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(1000);
	stop_Robot();
	motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(1000);
	stop_Robot();
	motor[frontrightmotor] = 127;
	motor[backrightmotor] = 127;
	motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(500);
	stop_Robot();
	motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(1000);
	stop_Robot();
	motor[frontrightmotor] = 127;
	motor[backrightmotor] = 127;
	motor[frontleftmotor] = 127;
	motor[backleftmotor] = 127;
	wait1Msec(1000);
	stop_Robot();


}






	// ..........................................................................

	// Insert user code here.

	// ..........................................................................








/*---------------------------------------------------------------------------*/

/*                                                                           */

/*                              User Control Task                            */

/*                                                                           */

/*  This task is used to control your robot during the user control phase of */

/*  a VEX Competition.                                                       */

/*                                                                           */

/*  You must modify the code to add your own robot specific commands here.   */

/*---------------------------------------------------------------------------*/



task usercontrol()

{

	// User control code here, inside the loop



	while (true)

	{

		// This is the main execution loop for the user control program.

		// Each time through the loop your program should update motor + servo

		// values based on feedback from the joysticks.



		// ........................................................................

		// Insert user code here. This is where you use the joystick values to

		// update your motors, etc.

		// ........................................................................



		// Use the left and right joysticks to control the left and right wheels

		motor[frontleftmotor]  = vexRT[Ch3];

		motor[backleftmotor]  = vexRT[Ch3];

		motor[frontrightmotor] = vexRT[Ch2];

		motor[backrightmotor] = vexRT[Ch2];



		// Use the 2nd controller right joystick to lift the dr4b

		motor[arm1] = vexRT[Ch2Xmtr2];
		motor[arm2] = vexRT[Ch2Xmtr2];
		motor[arm1top] = vexRT[Ch2Xmtr2];
		motor[arm2top] = vexRT[Ch2Xmtr2];





		// Use the 2nd controller left joystick to rotate the flipping mechanism

		motor[fliptable] = vexRT[Ch3Xmtr2];



	}

}
